/*
  Amboss/AmbossVersion.h
*/


#ifndef AMBOSS_CONFIG_VERSION_HPP_DEFINED
#define AMBOSS_CONFIG_VERSION_HPP_DEFINED


#define AMBOSS_VERSION_MAJOR @AMBOSS_VERSION_MAJOR@
#define AMBOSS_VERSION_MINOR @AMBOSS_VERSION_MINOR@
#define AMBOSS_VERSION_PATCH @AMBOSS_VERSION_PATCH@
#define AMBOSS_VERSION_SHA1 "@AMBOSS_VERSION_SHA1@"


#endif // AMBOSS_CONFIG_VERSION_HPP_DEFINED
