/*
  Amboss/AmbossVersion.h
*/


#ifndef AMBOSS_CONFIG_VERSION_HPP_DEFINED
#define AMBOSS_CONFIG_VERSION_HPP_DEFINED


#define AMBOSS_VERSION_MAJOR 0
#define AMBOSS_VERSION_MINOR 4
#define AMBOSS_VERSION_PATCH 1
#define AMBOSS_VERSION_SHA1 "0"


#endif // AMBOSS_CONFIG_VERSION_HPP_DEFINED
